## Generated by dust2 (version 0.3.28) - do not edit
RSV_ODE <- structure(
  function() get("RSV_ODE"),
  class = "dust_system_generator",
  name = "RSV_ODE",
  package = "RSVsim",
  path = NULL,
  parameters = data.frame(
    name = c("nAges", "nVaccStates", "b0", "b1", "phi", "delta", "gamma_s", "gamma_p", "gamma_vaccine", "nu", "omega_vect", "prop_detected_vect", "sigma_vect", "alpha_vect", "matrix_per_person", "VE", "Sp0", "Ep0", "Ip0", "Ss0", "Es0", "Is0", "R0", "Incidence0", "doses0", "nVaccTimes", "vaccine_times", "vaccine_cov", "vaccine_period"),
    type = c("int", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type"),
    constant = c(TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
    required = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 0L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 0L, 1L, 2L, 1L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
